V11 .json file and qualification plan MATE1/OCT
Open-Systems-Pharmacology/Cimetidine-Metformin-DDI pull request #1
Opened 2024-12-18 10:03 UTC by mgsc1020

please review @PavelBal

2025-01-23 10:33 UTC, PavelBal commented
Renam `Cimetidine-Metformin-DDI-V11.json` to `Cimetidine-Metformin-DDI.json`

2025-01-23 13:13 UTC, PavelBal commented
@Yuri05 @TWendl

This is for now the only DDI scenario for "qualification" of MATE/OCT1/OCT2 DDI:

![image](https://github.com/user-attachments/assets/3a0ab9e4-118a-4268-ad9a-0acde1aefe07)

I am not sure if a separate qualification report repository (like this one https://github.com/Open-Systems-Pharmacology/Qualification-DDI-P-gp) should be created, or should the qualification plan remain in this repo for now?

2025-01-23 14:03 UTC, PavelBal requested changes

2025-01-23 14:10 UTC, Yuri05 commented on Qualification/input/Content/titlepage.md
> +| Qualification Plan Release      | https://github.com/Open-Systems-Pharmacology/Qualification-OCT/MATE1/releases/tag/vx.x |
x.x is the version of the qualification plan. So usually 1.0 for the first release
y.y is the version of the OSP Suite (PK-Sim) version used

2025-01-23 14:11 UTC, Yuri05 commented
> I am not sure if a separate qualification report repository (like this one https://github.com/Open-Systems-Pharmacology/Qualification-DDI-P-gp) should be created, or should the qualification plan remain in this repo for now?

I think it's OK to leave the plan in this repo for the moment.
Please adjust the repo topics: remove `osp-model` and add `osp-qualification`.

2025-01-27 11:49 UTC, PavelBal commented
> Please adjust the repo topics: remove osp-model and add osp-qualification.

No can do, do not have the rights.

2025-01-27 11:59 UTC, PavelBal commented on README.md
>  Within this repository, we share a PK-Sim project file containing simulations of all published clinical studies used to evaluate the predictive performance of our models regarding the Cimetidine-Metf
Please change "share PK-Sim project" to "Share PK-Sim snapshot" (or how is this formulated in other DDI repos...)

2025-01-27 13:16 UTC, PavelBal commented
Move the DDI ratio data into https://github.com/Open-Systems-Pharmacology/OSP-PBPK-Model-Library

2025-01-30 11:05 UTC, Yuri05 commented
> > Please adjust the repo topics: remove osp-model and add osp-qualification.
> 
> No can do, do not have the rights.

ok, adjusted the topics

2025-09-19 13:16 UTC, mgsc1020 commented
@PavelBal @Yuri05 Yes, this was done and not closed

2025-09-19 13:29 UTC, merged

2025-09-19 13:29 UTC, PavelBal commented
@Yuri05 I can't merge